packages:
  - 'apps/*'
  - 'packages/*'
  - 'worker'

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: false
  workerd: true

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
