import type { DrizzleD1Database } from 'drizzle-orm/d1';
import type { RuntimeStateModel, RuntimeHistoryModel, RetryHistoryModel, RuntimeMetricModel } from '../schema';
export declare class RuntimeService {
    private runtimeStateRepository;
    private runtimeHistoryRepository;
    private retryHistoryRepository;
    private runtimeMetricsRepository;
    constructor(db: DrizzleD1Database<any>);
    getState(id: string): Promise<{
        id: string;
        currentState: string;
        health: string;
        lastExecutionStartedAt: Date | null;
        lastExecutionFinishedAt: Date | null;
        nextExecutionAt: Date | null;
        consecutiveFailures: number;
        cooldownUntil: Date | null;
        sessionStatus: string | null;
        sessionId: string | null;
        lastError: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | undefined>;
    ensureState(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        currentState: string;
        health: string;
        lastExecutionStartedAt: Date | null;
        lastExecutionFinishedAt: Date | null;
        nextExecutionAt: Date | null;
        consecutiveFailures: number;
        cooldownUntil: Date | null;
        sessionStatus: string | null;
        sessionId: string | null;
        lastError: string | null;
    }>;
    updateState(id: string, patch: Partial<Omit<RuntimeStateModel, 'id' | 'createdAt'>>): Promise<void>;
    recordRun(entry: Omit<RuntimeHistoryModel, 'id' | 'createdAt' | 'updatedAt'>): Promise<void>;
    recordRetry(entry: Omit<RetryHistoryModel, 'id'>): Promise<void>;
    recordMetrics(entry: Omit<RuntimeMetricModel, 'id' | 'createdAt' | 'updatedAt'>): Promise<void>;
    getRecentMetrics(limit?: number): Promise<{
        id: string;
        recordedAt: Date;
        jobsPerDay: number;
        appliesPerDay: number;
        reviewsPerDay: number;
        applySuccessRate: number;
        uptimePercent: number;
        averageScore: number;
        averageDurationMs: number;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    getRecentRetries(limit?: number): Promise<{
        id: string;
        runId: string;
        attempt: number;
        error: string;
        backoffMs: number;
        timestamp: Date;
    }[]>;
    getRecentHistory(limit?: number): Promise<{
        id: string;
        runType: string;
        state: string;
        status: string;
        startedAt: Date;
        finishedAt: Date | null;
        durationMs: number | null;
        jobsProcessed: number;
        autoApplies: number;
        reviewsCreated: number;
        successRate: number | null;
        errorMessage: string | null;
        metadata: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
}
